package com.hcl.saas.collector.model;

public class Constants {

    public static final String SLACK = "Slack";

    public static final String ZOOM = "Zoom";
    public static final String TOKEN = "eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJkN2JhNzQ0Zi00MmI2LTQ1MjctYjJmOS01MTY0OTA1NDc1MjMifQ.eyJ2ZXIiOjcsImF1aWQiOiI3MDhkMzNlZTkxNDZlOGYzOWZlNTExZmRjMDA1YTg5MiIsImNvZGUiOiJodkxTdEhjb1I5dTYzQmROeFhfc3RBNEM3MHlCQUhMUFciLCJpc3MiOiJ6bTpjaWQ6ZnpwbUtVSFNLaXBvZmdxV2ZpWXhRIiwiZ25vIjowLCJ0eXBlIjozLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiJ5UlpiYWttQ1FPeTBiZVVxdTBNaTl3IiwibmJmIjoxNjY2OTM4NTY2LCJleHAiOjE2NjY5NDIxNjYsImlhdCI6MTY2NjkzODU2NiwiYWlkIjoidnRCaG40ZlJUT213Q3F1WFZMR2hPUSIsImp0aSI6ImM4ZmRjODlmLTU5MjQtNDdjYi1hZDk3LTQzYTMzN2NhOWNmMSJ9.vQXhqolxlUzni6kuzBGClRerkt8yXh13mOi6j6OCMpOok1OumDAiMLZHOUfTkVsxPViIWLPY2D0uwGMxzstGNQ";
}
